name: Publish to Docker Hub
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-inference:latest $GITHUB_WORKSPACE
          docker inspect --format='{{.Id}}' ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-inference:latest | tee id.txt

      - name: Add image id to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: id.txt
          tag: ${{ github.ref }}
          overwrite: true

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/text-generation-inference:latest
          
          
